### ISSUE TITLE
AlgalID_vis

### ISSUE THREAD

**Issue by ecoff14** [coffm049/ogwtools#1]
I am trying to make the graph visualize nicely

library(ggpubr)
library(dplyr)
library(viridis)
library(hrbrthemes)

algalID <- read.csv("2022AlgalIDData.csv", header=TRUE, sep= ",", na.strings = c("ND"))

# Unnormalized area plot
algalID %>%
  filter(Site != 10) %>%
  ggplot(aes(x = Round, y = value, fill = Phyla)) +
  geom_area() +
  facet_wrap(~Site, scale = "free_y")

algalID <- algalID %>%
  mutate(Round=as.numeric(Round), value=as.numeric(value), Site=as.numeric(Site))%>%
  filter(Site !=10) %>%
  group_by(Round,Site, Phyla) %>%
  summarise(n = sum(value)) %>%
  mutate(percentage = n / sum(n) * 100)

# Note: you can also sort levels alphabetically:
myLevels <- levels(algalID$Phyla)
data$group <- factor(algalID$Phyla , levels=sort(myLevels) )

ggplot(algalID, aes(x=Round, y=percentage, fill=Phyla)) + 
  geom_area(alpha=0.6, linewidth=1, colour="black")+
  facet_wrap(~Site)

ggsave("C:/Users/coonee/Documents/Monitoring Projects/NearshoreHABs/2022/AlgalID.jpeg")

ggplot(algalID, aes(fill=Phyla, y=value, x=Site))+
  geom_bar(position="stack", stat="identity")+
  facet_wrap(~Round, scales="free_y")

ggplot(algalID, aes(fill=Phyla, y=value, x=Round))+
  geom_bar(position="stack", stat="identity")+
  facet_wrap(~Site, scales="free_y")

**Comment by coffm049** [comment]
Right now I have visualizations as barplots, I should convert the algalViz function to a different form of vizualization maybe stream or stacked area plots, or both
